name: ProjectName
version: 0.0.1
description: >-
  Place a description of your package here.
homepage: https://example.com
documentation: https://example.com
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  an_example: ^0.4.0
dev_dependencies:
  test: '>=1.15.0 <2.0.0'