name: compound_interest_calculator
version: 1.0.0
description: >-
  A simple compound interest calculator. Allows you to calculate future value,
  interest rate, principal, required contribution, and time periods.
homepage: https://github.com/Appsolutely-Wonderful/dart-compound-interest
documentation: https://github.com/Appsolutely-Wonderful/dart-compound-interest
environment:
  sdk: '>=2.10.0 <3.0.0'